# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Please Eat Good' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

 pod 'GeoFire', '~> 4.0'
  pod 'SwiftLocation', :git => 'https://github.com/malcommac/SwiftLocation.git', :tag => '5.0.3'
  pod 'CurrencyText'  
  pod 'PhoneNumberKit', '~> 3.1'
  pod 'SwiftDate'
  pod 'Firebase'
  pod 'Firebase/Storage'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'
  pod 'Firebase/InAppMessaging'
  pod 'URLImage'
  pod 'Firebase/Functions'
  pod 'SwiftyStoreKit'
  pod 'Firebase/MLVision'


  # Pods for Please Eat Good

end
